# Generated by Django 4.2.7 on 2023-11-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorder',
            options={'verbose_name_plural': 'Обработка заявок'},
        ),
        migrations.AlterModelOptions(
            name='designcategory',
            options={'verbose_name_plural': 'Категории дизайна'},
        ),
        migrations.AlterModelOptions(
            name='executor',
            options={'verbose_name_plural': 'Исполнитель'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='assigned_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.executor'),
        ),
    ]
